Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.10/dist-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Loading all of the parameters from the simple one-cell sim 
PnETGitHub_OneCellSim = parse_All_LANDIS_PnET_Files(r"/calibrationFolder/StartingCalibrationTest/SimulationFiles/PnETGitHub_OneCellSim")
print("\n\n\nHere is the big dictionnary with all of the parameters in it :\n\n" + str(PnETGitHub_OneCellSim))
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[2], line 2[0m
[1;32m      1[0m [38;5;66;03m# Loading all of the parameters from the simple one-cell sim [39;00m
[0;32m----> 2[0m PnETGitHub_OneCellSim [38;5;241m=[39m [43mparse_All_LANDIS_PnET_Files[49m[43m([49m[38;5;124;43mr[39;49m[38;5;124;43m"[39;49m[38;5;124;43m/calibrationFolder/StartingCalibrationTest/SimulationFiles/PnETGitHub_OneCellSim[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m      3[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;130;01m\n[39;00m[38;5;130;01m\n[39;00m[38;5;130;01m\n[39;00m[38;5;124mHere is the big dictionnary with all of the parameters in it :[39m[38;5;130;01m\n[39;00m[38;5;130;01m\n[39;00m[38;5;124m"[39m [38;5;241m+[39m [38;5;28mstr[39m(PnETGitHub_OneCellSim))

File [0;32m/calibrationFolder/calibrationJupyterBook/StartingCalibrationTest/functionsForCalibration.py:477[0m, in [0;36mparse_All_LANDIS_PnET_Files[0;34m(folder_path)[0m
[1;32m    474[0m results [38;5;241m=[39m {}  [38;5;66;03m# Initialize an empty dictionary to store results[39;00m
[1;32m    476[0m [38;5;66;03m# List all files in the specified directory[39;00m
[0;32m--> 477[0m [38;5;28;01mfor[39;00m filename [38;5;129;01min[39;00m [43mos[49m[38;5;241;43m.[39;49m[43mlistdir[49m[43m([49m[43mfolder_path[49m[43m)[49m:
[1;32m    478[0m     file_path [38;5;241m=[39m os[38;5;241m.[39mpath[38;5;241m.[39mjoin(folder_path, filename)
[1;32m    479[0m     [38;5;66;03m# Check if the file has a .txt extension[39;00m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/calibrationFolder/StartingCalibrationTest/SimulationFiles/PnETGitHub_OneCellSim'

